"""Changed Type error in Reservation

Revision ID: 04dc92b553b9
Revises: 51efed6eb9b9
Create Date: 2024-03-19 18:15:13.608769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dc92b553b9'
down_revision = '51efed6eb9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_adults', sa.Integer(), nullable=False))
        batch_op.drop_column('num_of_adault')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_of_adault', sa.INTEGER(), nullable=False))
        batch_op.drop_column('num_of_adults')

    # ### end Alembic commands ###
