"""Added Room number field

Revision ID: 87edbe3942bb
Revises: c978b030e7f4
Create Date: 2024-03-13 16:34:51.802550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87edbe3942bb'
down_revision = 'c978b030e7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.String(), nullable=False, server_default='default_value'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###
