"""Added Booking

Revision ID: 92b8ad645e4a
Revises: 87edbe3942bb
Create Date: 2024-03-15 15:58:11.572033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b8ad645e4a'
down_revision = '87edbe3942bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_num', sa.String(length=50), nullable=False),
    sa.Column('reservation_id', sa.String(length=60), nullable=False),
    sa.Column('service_id', sa.String(length=60), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('booked_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id'),
    sa.UniqueConstraint('service_id'),
    sa.UniqueConstraint('service_num')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('service_num', sa.VARCHAR(length=50), nullable=False),
    sa.Column('reservation_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('qty', sa.INTEGER(), nullable=False),
    sa.Column('booked_date', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id'),
    sa.UniqueConstraint('service_id'),
    sa.UniqueConstraint('service_num')
    )
    op.drop_table('booking')
    # ### end Alembic commands ###
