"""Room Number set to True

Revision ID: be95986030f8
Revises: 04dc92b553b9
Create Date: 2024-03-19 18:47:38.858120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be95986030f8'
down_revision = '04dc92b553b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
